// Code generated by protoc-gen-go. DO NOT EDIT.
// source: knowing.proto

// protoc --go_out=plugins=grpc:. knowing.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FindRequest struct {
	Tokens               []string `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	ArticleId            string   `protobuf:"bytes,2,opt,name=articleId,proto3" json:"articleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bd71b91024af0ec, []int{0}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

func (m *FindRequest) GetTokens() []string {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *FindRequest) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

type HasOptionResponse struct {
	Items                []*HasOption `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HasOptionResponse) Reset()         { *m = HasOptionResponse{} }
func (m *HasOptionResponse) String() string { return proto.CompactTextString(m) }
func (*HasOptionResponse) ProtoMessage()    {}
func (*HasOptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bd71b91024af0ec, []int{1}
}

func (m *HasOptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasOptionResponse.Unmarshal(m, b)
}
func (m *HasOptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasOptionResponse.Marshal(b, m, deterministic)
}
func (m *HasOptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasOptionResponse.Merge(m, src)
}
func (m *HasOptionResponse) XXX_Size() int {
	return xxx_messageInfo_HasOptionResponse.Size(m)
}
func (m *HasOptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HasOptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HasOptionResponse proto.InternalMessageInfo

func (m *HasOptionResponse) GetItems() []*HasOption {
	if m != nil {
		return m.Items
	}
	return nil
}

type HasOption struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Listen               int64    `protobuf:"varint,2,opt,name=listen,proto3" json:"listen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasOption) Reset()         { *m = HasOption{} }
func (m *HasOption) String() string { return proto.CompactTextString(m) }
func (*HasOption) ProtoMessage()    {}
func (*HasOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_4bd71b91024af0ec, []int{2}
}

func (m *HasOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasOption.Unmarshal(m, b)
}
func (m *HasOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasOption.Marshal(b, m, deterministic)
}
func (m *HasOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasOption.Merge(m, src)
}
func (m *HasOption) XXX_Size() int {
	return xxx_messageInfo_HasOption.Size(m)
}
func (m *HasOption) XXX_DiscardUnknown() {
	xxx_messageInfo_HasOption.DiscardUnknown(m)
}

var xxx_messageInfo_HasOption proto.InternalMessageInfo

func (m *HasOption) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *HasOption) GetListen() int64 {
	if m != nil {
		return m.Listen
	}
	return 0
}

func init() {
	proto.RegisterType((*FindRequest)(nil), "proto.FindRequest")
	proto.RegisterType((*HasOptionResponse)(nil), "proto.HasOptionResponse")
	proto.RegisterType((*HasOption)(nil), "proto.HasOption")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegionHandlerClient is the client API for RegionHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegionHandlerClient interface {
	GetListenAudio(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*HasOptionResponse, error)
}

type regionHandlerClient struct {
	cc *grpc.ClientConn
}

func NewRegionHandlerClient(cc *grpc.ClientConn) RegionHandlerClient {
	return &regionHandlerClient{cc}
}

func (c *regionHandlerClient) GetListenAudio(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*HasOptionResponse, error) {
	out := new(HasOptionResponse)
	err := c.cc.Invoke(ctx, "/proto.RegionHandler/GetListenAudio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegionHandlerServer is the server API for RegionHandler service.
type RegionHandlerServer interface {
	GetListenAudio(context.Context, *FindRequest) (*HasOptionResponse, error)
}

func RegisterRegionHandlerServer(s *grpc.Server, srv RegionHandlerServer) {
	s.RegisterService(&_RegionHandler_serviceDesc, srv)
}

func _RegionHandler_GetListenAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionHandlerServer).GetListenAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegionHandler/GetListenAudio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionHandlerServer).GetListenAudio(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegionHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RegionHandler",
	HandlerType: (*RegionHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetListenAudio",
			Handler:    _RegionHandler_GetListenAudio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "knowing.proto",
}

func init() { proto.RegisterFile("knowing.proto", fileDescriptor_4bd71b91024af0ec) }

var fileDescriptor_4bd71b91024af0ec = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x41, 0x4b, 0x03, 0x41,
	0x0c, 0x85, 0x59, 0xcb, 0x16, 0x26, 0xa5, 0xa2, 0x41, 0x64, 0x10, 0x0f, 0x65, 0x0f, 0xd2, 0x53,
	0x0f, 0xf5, 0x24, 0x82, 0x20, 0x82, 0xb6, 0x20, 0x14, 0xe6, 0x1f, 0xac, 0x4e, 0x28, 0x43, 0xd7,
	0x64, 0xdd, 0x49, 0xf1, 0xef, 0x8b, 0x33, 0x83, 0x2b, 0x78, 0x0a, 0xef, 0xbd, 0x90, 0xef, 0x05,
	0xe6, 0x07, 0x96, 0xaf, 0xc0, 0xfb, 0x55, 0x3f, 0x88, 0x0a, 0xd6, 0x69, 0x34, 0x4f, 0x30, 0x7b,
	0x0e, 0xec, 0x1d, 0x7d, 0x1e, 0x29, 0x2a, 0x5e, 0xc2, 0x54, 0xe5, 0x40, 0x1c, 0x6d, 0xb5, 0x98,
	0x2c, 0x8d, 0x2b, 0x0a, 0xaf, 0xc1, 0xb4, 0x83, 0x86, 0xf7, 0x8e, 0xb6, 0xde, 0x9e, 0x2c, 0xaa,
	0xa5, 0x71, 0xa3, 0xd1, 0xdc, 0xc3, 0xf9, 0xa6, 0x8d, 0xbb, 0x5e, 0x83, 0xb0, 0xa3, 0xd8, 0x0b,
	0x47, 0xc2, 0x1b, 0xa8, 0xb7, 0x4a, 0x1f, 0xf9, 0xd2, 0x6c, 0x7d, 0x96, 0xb9, 0xab, 0x71, 0x31,
	0xc7, 0xcd, 0x1d, 0x98, 0x5f, 0x0f, 0x2f, 0xa0, 0x4e, 0x44, 0x5b, 0x25, 0x46, 0x16, 0x3f, 0xad,
	0xba, 0x10, 0x95, 0x38, 0xa1, 0x27, 0xae, 0xa8, 0xf5, 0x0e, 0xe6, 0x8e, 0xf6, 0x41, 0x78, 0xd3,
	0xb2, 0xef, 0x68, 0xc0, 0x07, 0x38, 0x7d, 0x21, 0x7d, 0x4d, 0xe9, 0xe3, 0xd1, 0x07, 0x41, 0x2c,
	0xd8, 0x3f, 0x4f, 0x5e, 0xd9, 0x7f, 0x55, 0x4a, 0xe7, 0xb7, 0x69, 0x0a, 0x6e, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x7b, 0x5c, 0x0c, 0xb2, 0x2c, 0x01, 0x00, 0x00,
}
